# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Andrei Nasta
tagline:             '[into philosophy]'
description:         'research interests, drafts, etc.'
url:                 http://nastaa.github.io/
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Andrei Nasta
  url:               https://www.nastaa.org
  email:             and.nasta@gmail.com

# Custom vars
version:             1.0.0
